### ISSUE TITLE
Error at install "go build github.com/google/skylark/cmd/skylark" repl.go:33:2: cannot find package "github.com/chzyer/readline" in any of

### ISSUE THREAD

**Issue by SaintNazaire** [google/skylark#103]
**OS Platform and Distribution**

- Windows 10 professional
- Docker image based on Ubuntu:16.04.4 LTS (xenial)
- Docker 18.03.0-ce-win59

**Go install procedure**

```
curl https://dl.google.com/go/go1.10.1.linux-amd64.tar.gz -o /go1.10.1.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.10.1.linux-amd64.tar.gz && rm go1.10.1.linux-amd64.tar.gz
export PATH = $PATH:/usr/local/go/bin
```
**Exact command to reproduce**

```
go get github.com/google/skylark
go build github.com/google/skylark/cmd/skylark

```
triggers the following

**Error message**

> root/go/src/github.com/google/skylark/repl/repl.go:33:2: cannot find package "github.com/chzyer/readline" in any of:
>         /usr/local/go/src/github.com/chzyer/readline (from $GOROOT)
>         /root/go/src/github.com/chzyer/readline (from $GOPATH)

**Comment by alandonovan** [comment]
Thanks for the report. Now that we have an external dependency, we have to get exactly what we build, so the updated command is: `go get github.com/google/skylark...`

Doc updated by https://github.com/google/skylark/commit/06804d924f8f4f36e25d858d0eb0bab8e1c8bc80
