### ISSUE TITLE
feature request: allow custom skylark Values to implement the slice operator

### ISSUE THREAD

**Issue by nicks** [google/skylark#104]
in real Python, user-defined classes can implement the slice operator (`x[i:j]`)

in Skylark, the slice operator can only be used on String, List, and Tuple
https://github.com/google/skylark/blob/master/eval.go#L883

would you accept a PR to make this an interface, like other Skylark operators (HasAttrs, etc)?

**Comment by alandonovan** [comment]
In principle, yes.
