### ISSUE TITLE
Resolving global variables

### ISSUE THREAD

**Issue by laurentlb** [google/skylark#116]
Example 1:
```python
def f():
    print(len)
    len = 2
    print(len)

f()
```

Example 2:
```python
print(len)
len = 2
print(len)
```

The first example fails, because `local variable len referenced before assignment`. The second example should fail for the same reason.

From the spec: "If name is bound anywhere within a block, all uses of the name within the block are treated as references to that binding, even uses that appear before the binding."

**Comment by alandonovan** [comment]
Thanks for reporting this.

I wonder what the correct semantics should be. You said it should be a dynamic error, just like the local variable, but I notice Python (2 and 3) implement the same semantics as the Go implementation: the first reference to len refers to the predeclared name, though I cannot derive this interpretation from the spec, https://docs.python.org/3.3/reference/executionmodel.html#execution-model.

BTW, the Bazel implementation is confusing in a different way. In Example 1, it resolves the first print(len) within f to the predeclared function len and prints "<built-in function len>". Then, execution of the len=2 assignment fails with the strange error "Variable 'len' is referenced before assignment. The variable is defined in the global scope"; removing the first print causes the assignment to succeed, oddly.  In Example 2, The assignment to len fails statically with "Variable len is read only". This is at odds with the spec, and these semantics prevent you from adding new names to the predeclared block without breaking existing programs. But I'm sure you were aware of these issues already.
