### ISSUE TITLE
Plan for transition to starlark rename?

### ISSUE THREAD

**Issue by b5** [google/skylark#127]
It seems skylark has landed on it's rename to starlark. Is there a plan for renaming this package?

**Comment by alandonovan** [comment]
Yes. I plan to rename the interpreter to starlark,net/starlark. I'm currently waiting for the Bazel team to run the web server on that domain that will serve go list redirects.

**Comment by dgryski** [comment]
What's the plan for the exiting issues and open PRs?

**Comment by alandonovan** [comment]
I'm working through them, applying the changes to the new repo. The old repo is effectively frozen at this point.
