### ISSUE TITLE
string.capitalize

### ISSUE THREAD

**Issue by laurentlb** [google/skylark#140]
According to the specification and the implementation, `string.capitalize` modifies the first letter of every word. Therefore `"aBc dEf".capitalize()` returns `"ABc DEf"`.

This is a bug:

* This is inconsistent with both Bazel and Python, because they return `"Abc def"`.
* `string.capitalize` seems redundant with  behave as `string.title`.

**Comment by alandonovan** [comment]
I agree this is a bug. Thanks for reporting it.
