### ISSUE TITLE
Support type annotations

### ISSUE THREAD

**Issue by gonzojive** [google/skylark#144]
.bzl files suffer from the same type safety problems as as untyped Python. It is much harder for me to trace through .bzl coded compared to Go.

Is there any work to support static type declarations? Copying Python's type semantics seems most natural since the syntax of the languages is so close.

**Comment by alandonovan** [comment]
This repository is defunct; the project has moved to go.starlark.net.

For this issue, see discussion at https://github.com/bazelbuild/starlark/issues/106.
