### ISSUE TITLE
Operator implementations?

### ISSUE THREAD

**Issue by natefinch** [google/skylark#21]
I'm working on time and duration.  I'd like to be able to do something like

```python
duration = time1 - time2
```

however, it looks like operators are hard coded right now. Could that be defined as an interface to implement, like Comparable?

Ideally I'd like to be able to do

```python
time2 = time1 + duration
```

So unlike CompareSameType, it would not require the two to be the same type.  The function would need to figure out the type and behave accordingly.

**Comment by alandonovan** [comment]
A user-defined type can participate in arithmetic and other binary operators by implementing the HasBinary interface.  (There's no counterpart for unary operators such as -x.)

**Comment by natefinch** [comment]
Ahh, oops, missed that. Thanks!
