### ISSUE TITLE
Please don't change the name

### ISSUE THREAD

**Issue by natefinch** [google/skylark#3]
I really like the name skylark.  It's evocative, makes for a nice file extension - .sky... opens up a lot  of unused namespaces in the go community.

**Comment by mattn** [comment]
As far as I know, skylark is Go port of bazel configuration language.

https://docs.bazel.build/versions/master/skylark/

If you replace bazel with Go, the name should be remained. But if you are going to make standalone implementation, I suggest to change the name.

**Comment by alandonovan** [comment]
Nate: I really like the name too, but the decision is not mine to make; it's up to the Bazel team and Google's lawyers.

Matt: historically Skylark was the same thing as Bazel's build language, but they are now separate concepts. Skylark is the core language (of which this project is a Go port), and Bazel's build language is Skylark extended with dozens of domain-specific functions such as 'rule' and 'glob'.  Other applications besides Bazel use Skylark as the core of their configuration language, and we anticipate still more, in both Java and Go.

**Comment by natefinch** [comment]
Hmm, lawyers, boo.  Ok, well, maybe we'll get lucky :)
