### ISSUE TITLE
hashtable: sprinkle per-table salt into hash(x) before choosing a bucket

### ISSUE THREAD

**Issue by alandonovan** [google/skylark#33]
Currently the hash table used by dict and set uses `slot = hash(x) % len(table)` to choose a bucket.  This is vulnerable to hash flooding, a denial of service attack in in which the adversary chooses values of x that result in the same slot, causing the table to degenerate to a single bucket and server performance to suffer.

To mitigate this, we'll need to change the signature of `Value.Hash` to accept a seed value, and change implementations to incorporate this seed value into their result in an order-dependent manner, such as multiplication but not simply XOR. Each table will need to provide a random seed value, created during table initialization and constant for the life of each table, to `hash(x, seed)`.  It is not sufficient to merely incorporate the seed value after computing `hash(x)`.

This will not change the semantics of the hash table observed by the Skylark program; in particular, iteration will still be in insertion order.

**Comment by funny-falcon** [comment]
>  It is not sufficient to merely incorporate the seed value after computing hash(x).

There is a need in global seed. Per table seed could be mixed after hashing then:
`h=hash(x, globalSeed)+tableSeed; h^=h>>16; h*=0xcafebeef; h^=h>>16;` (Instead 0xcafebeef choose any random looking odd constant)

But it makes sense only if object may cache its hash value. Otherwise, hashing with table seed is preferred.

**Comment by alandonovan** [comment]
An object may not cache its hash value, as it should vary from one hashtable to another.

**Comment by funny-falcon** [comment]
I've presented in previous comment how cached hash value could be mixed with per-table seed.

There is still need in global per-process safe random seed, though.

**Comment by alandonovan** [comment]
Closing as infeasible; see https://github.com/google/skylark/pull/38#issuecomment-356430056
