### ISSUE TITLE
syntax.Parse not parsing based on the type of src

### ISSUE THREAD

**Issue by peterebden** [google/skylark#59]
A smallish example:
```
package main

import (
	"fmt"

	"github.com/google/skylark/syntax"
)

func test1(filename string, src []byte) error {
	_, err := syntax.Parse(filename, src)
	return err
}

func test2(filename string, src interface{}) error {
	_, err := syntax.Parse(filename, src)
	return err
}

func main() {
	fmt.Printf("%s\n", test1("test.sky", nil))
	fmt.Printf("%s\n", test2("test.sky", nil))
}
```
which prints
```
%!s(<nil>)
reading test.sky: open test.sky: no such file or directory
```

This is a little surprising; you'd expect both to do the same thing, but if `src` is passed as a nil `[]byte` instead of an untyped nil, it's still used. From reading the docs, I assume that's not what's intended.

Happy to send a little PR for this if you agree.

**Comment by alandonovan** [comment]
This is the intended behavior.  In the second call, of test2, the nil src indicates that the parser should open the named file; this is expected to be the typical usage. In the first call, of test1, the non-nil src indicates that the parser should pretend that the input came from the named file (when printing file names in diagnostics), but should in fact read input from the specified source of bytes.

A nil value of type interface{} is not the same as an interface{} value containing a nil reference, such as a pointer, map, channel, func, or in this case, slice.

**Comment by peterebden** [comment]
Yup, I understand the distinction between the two, just suggesting that it was confusing (at least for me) and a little unusual that I could fix it by changing my function to accept `interface{}` instead of `[]byte`.

Fine if this is the intended behaviour, though.

**Comment by alandonovan** [comment]
I copied this part of the API verbatim from go/parser. It has a bit of an "untyped" feel to it, and it penalizes you if you write a typed wrapper (as you did), but it's simple and flexible and much nicer than various "InputSource" abstractions I've seen over the years.
