### ISSUE TITLE
Bazel-Like Rule Attribute Library

### ISSUE THREAD

**Issue by pcj** [google/skylark#62]
This project is great! I'm just in the beginning stages of using it for a custom configuration language.  Here is an example builtin callback:

```python
# test.sky
local_workspace(
    name = "foo",
    root = ".",
    files = ["a.txt", "b.txt"],
)
```

```python
func (i *Interpreter) handleLocalWorkspace(thread *skylark.Thread, _ *skylark.Builtin, args skylark.Tuple, kwargs []skylark.Tuple) (skylark.Value, error) {
	rule := &LocalWorkspaceRule{}
	files := skylark.NewList([]skylark.Value{})
	
	if err := skylark.UnpackArgs("local_workspace", args, kwargs,
		"name", &rule.Name,
		"root?", &rule.Root,
		"files?", &files,
	); err != nil {
		return nil, err
	}

	if rule.Name == "" {
		return nil, fmt.Errorf("local_workspace attribute 'name' is required")
	}

	iter := files.Iterate()
	defer iter.Done()
	var value skylark.Value
	for iter.Next(&value) {
		log.Printf("filename: %v\n", value)
		if value.Type() == "string" {
			rule.Files = append(rule.Files, value.String())
		} else {
			return nil, fmt.Errorf("`files` attribute element must be a string, not %s (%v)", value.Type(), value.String())
		}
	}

	i.LocalWorkspaceRule = append(i.LocalWorkspaceRule, rule)
	return skylark.None, nil
}
```
Here I've defined a "rule" called `local_workspace`.  This works!  

However, I immediately find myself wondering if there is an existing library or plans to support bazel-like custom rule definitions, where I don't have to do all the validation myself.  Basically, I'd like to be able to build up custom rule definitions that have string_list attributes (in Go), and have the rule automap the args to some struct type or protobuf type.

This of course is not terribly hard to write, but it seems like something that may already be in the works so I thought I'd ask.

**Comment by pcj** [comment]
Based on lack of response for this issue, I'll assume there are not immediate plans to implement the above.

**Comment by alandonovan** [comment]
Sorry for not responding sooner, but you are right: there are no such plans.  The general criteria for adding stuff to this (or any) project should be (1) can we live without it? and (2) is there one clearly superior design that will serve many users well? In this case, (1) there's no good reason for this code to live in the Skylark interpreter as it's entirely client-specific behavior, furthermore specific to only one client, and (2) the thing you're asking for is rather ad hoc; one can imagine a dozen slightly different ways of doing it.

As you said, it's not terribly hard to write.

**Comment by pcj** [comment]
SGTM.  I'll repost a link here if I write one.
