### ISSUE TITLE
Preserve comments in the AST

### ISSUE THREAD

**Issue by laurentlb** [google/skylark#63]
The parser should have an option to capture the comments and attach them to AST nodes (https://talks.go-zh.org/2015/gofmt-en.slide#31). For convergence, we probably want to do like in Buildifier (https://github.com/bazelbuild/buildtools/blob/master/build/syntax.go#L59).

Comments are useful for a wide range of applications (linter, formatting, refactoring...).

**Comment by alandonovan** [comment]
Good idea.  Paul Bethe had expressed interest in working on a pretty-printer for Skylark in Go. I don't know how far he got, but talk to him before you spend any significant time coding.

**Comment by alandonovan** [comment]
Done in PR #64.
