### ISSUE TITLE
Add Bazel support

### ISSUE THREAD

**Issue by abergmeier** [google/skylark#81]
It feels very weird to have a Skylark implementation, that I cannot build with Bazel.

**Comment by pcj** [comment]
FWIW, `go_repository` (gazelle) works just fine with this repo so it's pretty easy to build with bazel.

**Comment by alandonovan** [comment]
Gazelle is the recommended way to create BUILD files from projects buildable with 'go build'.

**Comment by abergmeier** [comment]
> Gazelle is the recommended way to create BUILD files from projects buildable with 'go build'.

You do realize, that this then means e.g. testing with Bazel is not working, right?
