### ISSUE TITLE
resolve.File: isBuiltin arg is confusing

### ISSUE THREAD

**Issue by natefinch** [google/skylark#9]
https://godoc.org/github.com/google/skylark/resolve#File

resolve.File takes an arg isBuiltIn.... I thought this was supposed to return true both for builtins in skylark.Universe, and for ones I passed in as globals, since the ones I pass in are created are of type skylark.BuiltIn.  However, when I do that, I get nil pointer panics (will create another bug for that).  I think there's a couple problems here:

1. Calling functions you create and pass in as globals "builtins" is very confusing. They're not "built in" per se, even if they're also not defined in the script itself.

2. resolve.File seems to have a different definition of what a builtIn is, which seems to want only things in skylark.Universe.  And if that's so, why do I need to pass in an argument for that at all?

**Comment by alandonovan** [comment]
The documentation could certainly be improved. 

The two predicates represent different sets of identifiers.  isBuiltin reports whether an identifier is predefined in the universe; the universe is shared between all modules, and its values must be stateless.  isPredeclaredGlobal reports whether an identifier is predefined in the module's globals; the set of such identifiers may vary from one module to another, and their values can be stateful.  A typical call to resolve.File passes the `StringDict.has` method bound to a particular `StringDict`; that is, `Universe.has` or `globals.has`, though of course `has` is a private method so you have to write it out in full if you're outside the evaluator package.  Perhaps we should export `StringDict.Has`.

"Builtin" is an overloaded term in the Go API.  In addition to its use in the spec ("a function or method implemented in Go") it also means "a name in the Universe block".  Perhaps we should use the term "universal" for the latter.

**Comment by alandonovan** [comment]
See https://github.com/google/skylark/pull/11

**Comment by natefinch** [comment]
#11 resolves this :)
