### ISSUE TITLE
Information missing in the AST due to string concatenation

### ISSUE THREAD

**Issue by laurentlb** [google/skylark#91]
The AST is relatively faithful to the input file and contains a lot of information (locations, raw data). One notable exception is due to an optimization in the parser: `"a" + "b"` is replaced with `"ab"`.

Is there a way to preserve this information?
Maybe optimizations on the AST could be done in a separate pass (in case we want to do other things like this)?

**Comment by alandonovan** [comment]
Currently there is not, but I agree optimizations should be done as an optional separate pass, perhaps by the resolver (or by the bytecode compiler if I ever decide to commit it).

**Comment by alandonovan** [comment]
I've committed the compiler (https://github.com/google/skylark/pull/95) and sent a PR to move the string-concatenation optimization out of the parser (https://github.com/google/skylark/pull/97).

**Comment by alandonovan** [comment]
Fixed now.

**Comment by laurentlb** [comment]
Thanks!
